In [12]:
import numpy as np

from math import comb

## Task 2

In [4]:
arr1 = [ comb(10, 2*i) for i in range(6) ]
arr2 = [ comb(2*i, i) for i in range(6)]

In [5]:
arr1

[1, 45, 210, 210, 45, 1]

In [8]:
arr2[::-1]

[252, 70, 20, 6, 2, 1]

In [9]:
arr3 = []
for a1, a2 in zip(arr2, arr2[::-1]):
    arr3.append(a1*a2)

In [10]:
arr3

[252, 140, 120, 120, 140, 252]

In [11]:
ans = 0
for a1, a2 in zip(arr1, arr3):
    ans += a1*a2
ans

63504

Answer: 63504

## Task 4

0.615

## Task 1

In [13]:
class GermGraph:

    def __init__(self) -> None:
        self.power_of_apex = [3,3,3,2,4,3]
        self.current_germs = [1,1,1,1,1,1]
        self.graph = np.array([[0,1,1,0,1,0],
                               [1,0,0,1,1,0],
                               [1,0,0,0,1,1],
                               [0,1,0,0,0,1],
                               [1,1,1,0,0,1],
                               [0,0,1,1,1,0]])
        
    def step(self):
        for i in range(6):
            for j in range(6):
                self.current_germs[i] += self.current_germs[j] if self.graph[i][j] == 1 else 0

    

In [14]:
g = GermGraph()

In [15]:
for _ in range(16):
    g.step()

In [16]:
g.current_germs

[209013048485833337,
 409054988700990089,
 603744912122724833,
 692871105199902769,
 1571366707673076177,
 3099951441867590681]

## Task 8

In [44]:
def matrix_mod_power(matrix, exp, mod):
    """
    Efficiently computes matrix to the power of exp with modulo mod.
    """
    # Start with an identity matrix of the same size as the input matrix
    result = np.eye(matrix.shape[0], dtype=np.ulonglong)
    
    # Copy the matrix to avoid modifying the original matrix
    matrix = np.copy(matrix)

    while exp > 0:
        # If exp is odd, multiply the result with the current matrix
        if exp % 2 == 1:
            result = (result @ matrix) % mod

        # Square the matrix and reduce exp by half
        matrix = (matrix @ matrix) % mod
        exp //= 2

    return result

In [45]:
matrix_mod_power(step, 10**9, modfactor)

array([[        0,    121393, 999924982],
       [        0, 999924982,     46368],
       [        0,     46368, 999971350]], dtype=uint64)

In [51]:
import numpy as np
from numpy.linalg import matrix_power

def matrix_mod_power(matrix, exp, mod):
    """
    Efficiently computes matrix to the power of exp with modulo mod.
    """
    # Start with an identity matrix of the same size as the input matrix
    result = np.eye(matrix.shape[0], dtype=np.ulonglong)
    
    # Copy the matrix to avoid modifying the original matrix
    matrix = np.copy(matrix)

    while exp > 0:
        # If exp is odd, multiply the result with the current matrix
        if exp % 2 == 1:
            result = (result @ matrix) % mod

        # Square the matrix and reduce exp by half
        matrix = (matrix @ matrix) % mod
        exp //= 2

    return result

a3 = np.array([[0,1,1], [0,1,0], [0,0,1]])
a2 = np.array([[1,0,0], [1,0,1], [0,0,1]])
a1 = np.array([[1,0,0], [0,1,0], [1,1,0]])

step = (a1 @ (a2 @ a3)).astype(np.ulonglong)

modfactor = 1000000007 

num_of_input_data = int(input())

# ans = []
for _ in range(num_of_input_data):
    n, k = input().split(' ')
    init_arr = np.array(input().split(' '), dtype=np.ulonglong) % modfactor
    operator = matrix_mod_power(step, int(k), modfactor)
    ans = (operator @ init_arr) % modfactor
    print(*ans, sep=' ')

ValueError: invalid literal for int() with base 10: ''

In [41]:
matrix_power(step, 2* 10**6)

array([[                   0,  7497720437536903935,  3158300221159902977],
       [                   0,  3158300221159902977, 10656020658696806912],
       [                   0, 10656020658696806912, 13814320879856709889]],
      dtype=uint64)

## Task 9

In [73]:
n = int(input())
m = int(input())
matrix = []
for _ in range(n):
    row = input().split(',')
    row = [int(number.strip()) for number in row]
    matrix.append(row)
matrix = np.array(matrix)

In [74]:
matrix

array([[1, 3, 1, 2, 5],
       [1, 3, 4, 2, 5],
       [4, 4, 4, 0, 1]])

In [76]:

def R(i, j):

    if (i == 0) and (j == 0):
        return matrix[i,j]
    
    if (i < 0) or (i>j):
        return -100
    
    return matrix[i, j] + max(R(i-1, j-1), R(i, j-1))
    

In [77]:
R(n-1,m-1)

11

In [68]:
matrix

array([[1, 3, 1, 1],
       [1, 2, 2, 2],
       [4, 2, 1, 0]])